name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: checkboxes
    id: known-issue
    attributes:
      label: Is this a known issue?
      description: Please search through our [Known Issues](../../docs/KNOWN_ISSUES.md) to see if this bug has been reported.
      options:
        - label: I have searched the existing issues
          required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Please include relevant screenshots
      value: "A wild bug appeared!"
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Describe the expected behavior
      value: "I would expect..."
    validations:
      required: true

  - type: textarea
    id: to-reproduce
    attributes:
      label: Include steps to reproduce
      value: "Steps to reproduce:"
    validations:
      required: true

  - type: dropdown
    id: platforms
    attributes:
      label: What platforms are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Microsoft Edge
        - Opera
        - Safari
        - Electron

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: input
    id: session-id
    attributes:
      label: Session ID
      placeholder: 1_abc123def456-fn4

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../../CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
