blank_issues_enabled: false
contact_links:
  - name: Need help with running Vonage Video API React Application?
    url: https://api.support.vonage.com/hc/en-us
    about: Check out our support page.
